#!/usr/bin/env groovy

@Library("jenkins-shared-library-test@master")_
pipeline {
  agent { label "build" }
  stages {
    stage('pre build') {
      steps {
        sh "echo 'pre build'"
        sh "sleep 1"
        script {
          def helloMsg=sayHello("pipeline")
          echo "${helloMsg}"
        }
      }
    }
    stage('build') {
      steps {
        sh "echo 'build'"
        sh "sleep 1"
      }
    }
    stage("post build") {
      steps {
        sh "echo 'post build'"
        sh "sleep 1"
      }
    }
  }
}