#!/usr/bin/env groovy

pipeline {
  agent { label "build" }
  stages {
    stage('pre build') {
      steps {
        sh "echo 'pre build'"
      }
    }
    stage('build') {
      steps {
        sh "echo 'build'"
      }
    }
    stage("post build") {
      steps {
        sh "echo 'post build'"
      }
    }
  }
}