#!/usr/bin/env groovy

pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'build"'
      }
    }
    stage('Post Build') {
      steps {
        sh 'post build'
      }
      stage("post post stage") {
        steps {
          sh 'post post build'
        }
      }
    }
  }
}